[package]
name = "hydroponics-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
http = "1.1.0"
reqwest = "0.12.9"
tokio = {version = "1.41.1", features = ["full"]}
url = "2.5.4"
